### ISSUE TITLE
Enterprise Edition License Header

### ISSUE THREAD

**Issue by Vinai** [techdivision/TechDivision_MagentoUnitTesting#2]
The following files are distributed under the Enterprise Edition License:
- src/app/bootstrap.php
- src/app/code/community/Mage/Adminhtml/Block/Widget/Grid/Column/Renderer/Interface.php
- src/app/code/community/Mage/Install/Model/Installer/Console.php
- src/app/code/community/Mage/Install/Model/Installer/Db/Mysql4.php

Not sure what needs to be done about it, but it seems like a thing that should be checked if it's correct and permitted.

**Comment by wagnert** [comment]
I Vinai, your right. This was a mistake. I'll update the licence information and push a new version.

**Comment by wagnert** [comment]
I've changed the licence information of the responding file and pushed the changes. Thanks for your attention and your hint.
