### ISSUE TITLE
${namespace} in phpunit.xml.local - what is this?

### ISSUE THREAD

**Issue by andkirby** [techdivision/TechDivision_MagentoUnitTesting#28]
Guys, could you help with this? I really don't know how it works. :)

**Comment by dmcdaniel12** [comment]
It's your namespace. If you want to test your own modules, you would change it to whatever your namespace is.

**Comment by andkirby** [comment]
I mean can it be automatically replaced in some cases? I found similar variables in PHPUnit library.

**Comment by wick-ed** [comment]
It does look like [ANT build properties](http://www.tutorialspoint.com/ant/ant_property_files.htm) to me.
Have a look [here](https://github.com/techdivision/TechDivision_MagentoUnitTesting/blob/github/build.xml#L16). These values most likely get substituted by ANT when preparing the dev environment. You can overwrite it by placing a `build.properties` file within the libraries base directory and specify your values there. It will override any value as specified in the `build.xml` file.
How the actual substitution is triggered beats me but I suspect it is located in an ANT target within the `${build.dir}/general.xml` file.

**Comment by vadimjustus** [comment]
The `build.xml` and `build.default.properties` files are part of your companies build and deployment driven by [ANT](https://ant.apache.org/). You can implement your own built logic in `build/general.xml`.
The origin definition of ${namespace} is here: https://github.com/techdivision/TechDivision_MagentoUnitTesting/blob/github/build.xml#L16. You can overwrite it within a `build.properties` file.

**Comment by vadimjustus** [comment]
Oh, @wick-ed was faster - Thanks ;)

**Comment by wick-ed** [comment]
You are most certainly welcome @vadimjustus ;)

**Comment by andkirby** [comment]
Many thanks for your answers! :)
