### ISSUE TITLE
Testsuite throws an Fatal Exception

### ISSUE THREAD

**Issue by azngeek** [techdivision/TechDivision_MagentoUnitTesting#4]
The Testsuite will throw a fatal exception:

 phpunit -c phpunit.xml.dist 
PHP Warning:  include(Magento/Exception.php): failed to open stream: No such file or directory in /srv/testing/src/lib/Varien/Autoload.php on line 93
PHP Warning:  include(): Failed opening 'Magento/Exception.php' for inclusion (include_path='/srv/testing/src/dev/tests/integration/framework:/srv/testing/src/dev/tests/integration/testsuite:/srv/testing/src/app/code/local:/srv/testing/src/app/code/community:/srv/testing/src/app/code/core:/srv/testing/src/lib:/srv/testing/src/dev/tests/integration/.:.:/usr/share/php:/usr/share/pear') in /srv/testing/src/lib/Varien/Autoload.php on line 93
PHP Fatal error:  Class 'Magento_Exception' not found in /srv/testing/src/dev/tests/integration/framework/Magento/Test/Bootstrap.php on line 364

It seems like that the File Magento/Exception is not available. Is this part of the magento 2 installation?

Setup:

Plain Magento 1.7.0.2 installation.
Extension installed into the directory as explained in the blog.

**Comment by nhp** [comment]
Had the same issue and could solve it with a comment from the blog: dev/tests/integration/tmp was missing. creating the tmp directory solved it for me.
