### ISSUE TITLE
Relies on Magento_Profiler, a Magento2 class

### ISSUE THREAD

**Issue by maderlock** [techdivision/TechDivision_MagentoUnitTesting#7]
There are a number of files which reference Magento_Profiler. However, in Magneto 1, isn't this called Varien_Profiler? If their use is similar enough, it should be possible to replace the calls to Magento_Profiler with Varien_Profiler. I will try this on my fork.

Thanks,
Rob Egginton

**Comment by vadimjustus** [comment]
Changes merged - issue closed
